apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: tilt-avatar-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tilt-avatar-api
  template:
    metadata:
      labels:
        app: tilt-avatar-api
    spec:
      containers:
        - name: tilt-avatar-api
          image: tilt-avatar-api
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: '/ready'
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: tilt-avatar-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
